definitions:
  api.changeBalance:
    properties:
      amount:
        type: integer
    type: object
info:
  contact: {}
paths:
  /{id}:
    get:
      description: Get the balance of a user by user ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: User balance
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get balance of a user
      tags:
      - Balance
    post:
      consumes:
      - application/json
      description: Increase the balance of a user by a specified amount.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Balance change amount
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.changeBalance'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Increase user balance
      tags:
      - Balance
    put:
      consumes:
      - application/json
      description: Decrease the balance of a user by a specified amount.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Balance change amount
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.changeBalance'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Decrease user balance
      tags:
      - Balance
swagger: "2.0"
